# Generated by Django 4.0 on 2022-02-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0002_post_video_postvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvideo',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.DeleteModel(
            name='postVideo',
        ),
    ]
