# Generated by Django 4.0 on 2022-01-27 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='../static/ProfileImgs')),
                ('background_photo', models.ImageField(upload_to='../static/ProfileImgs')),
                ('phoneNumber', models.IntegerField(max_length='13', null=True)),
                ('country', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('followers', models.ManyToManyField(related_name='related_to', through='ProfilePage.Follower', to='ProfilePage.Users')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareName', models.CharField(max_length=50)),
                ('shareType', models.CharField(max_length=50)),
                ('shareDescription', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfilePage.users')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postType', models.CharField(max_length=50)),
                ('postDescription', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfilePage.users')),
            ],
        ),
        migrations.AddField(
            model_name='follower',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='ProfilePage.users'),
        ),
        migrations.AddField(
            model_name='follower',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='ProfilePage.users'),
        ),
    ]
