# Generated by Django 4.0 on 2022-01-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumber',
            field=models.IntegerField(null=True),
        ),
    ]
