# Generated by Django 4.0 on 2022-02-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooker',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
