# Generated by Django 4.0.1 on 2022-02-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePage', '0002_alter_cooker_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooker',
            old_name='country',
            new_name='Nationality',
        ),
    ]
