# Generated by Django 3.1.7 on 2022-05-09 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_profile_followers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Profile_profile_followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='Account.user', verbose_name='user')),
                ('profile_image', models.ImageField(default='avatars/guest.png', upload_to='avatars/')),
                ('cover_image', models.ImageField(default='avatars/cover.png', upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('about', models.TextField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
